version: '3'
services:
  backend:
    build: .
    ports:
      - 8000:5000
    env_file:
    - path: .env
      required: true
    volumes:
      - .:/email-backend
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    